/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import API from '../../api/axios';
import BorrowStatusBadge from '../../components/common/BorrowStatusBadge';
import { formatDateTime } from '../../utils/date';
import { getApiErrorMessage } from '../../utils/apiError';

export default function BorrowCardDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const [card, setCard] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { const { data } = await API.get(`/borrow-cards/${id}`); setCard(data); } catch (err) { setError(getApiErrorMessage(err, 'Không thể tải phiếu mượn.')); } };
  useEffect(() => { load(); }, [id]); // eslint-disable-line react-hooks/exhaustive-deps
  const action = async (name) => { let endpoint = `/${name}`; let payload; if (name === 'renew') { const dueDate = window.prompt('Nhập hạn trả mới (YYYY-MM-DD):'); if (!dueDate) return; payload = { dueDate: `${dueDate}T23:59:59.000Z` }; } if (name === 'cancel' && !window.confirm('Hủy phiếu và hoàn toàn bộ sách về kho?')) return; if (name === 'return' && !window.confirm('Xác nhận độc giả đã trả toàn bộ sách?')) return; setBusy(true); setError(''); try { await API.patch(`/borrow-cards/${id}${endpoint}`, payload); await load(); } catch (err) { setError(getApiErrorMessage(err, 'Không thể xử lý phiếu.')); } finally { setBusy(false); } };
  if (!card) return <div className="page">{error ? <div className="alert alert-error">{error}</div> : <div className="loading-panel">Đang tải...</div>}</div>;
  const active = ['borrowed', 'overdue'].includes(card.status);
  return <div className="page"><div className="page-header"><div><h1>Chi tiết phiếu mượn</h1><p className="page-subtitle">Mã phiếu: {card._id}</p></div><div className="actions">{card.status === 'borrowed' && <Link className="btn btn-edit" to={`/borrow-cards/${id}/edit`}>Sửa phiếu</Link>}{active && <><button disabled={busy} className="btn btn-primary" onClick={() => action('return')}>Xác nhận trả sách</button><button disabled={busy} className="btn btn-secondary" onClick={() => action('renew')}>Gia hạn</button><button disabled={busy} className="btn btn-delete" onClick={() => action('cancel')}>Hủy phiếu</button></>}</div></div>{error && <div className="alert alert-error">{error}</div>}<div className="detail-grid"><section className="detail-card"><h2>Độc giả</h2><dl className="detail-list"><div><dt>Họ tên</dt><dd>{card.reader?.name}</dd></div><div><dt>Email</dt><dd>{card.reader?.email}</dd></div></dl></section><section className="detail-card status-summary"><h2>Trạng thái</h2><BorrowStatusBadge status={card.status} /><dl className="detail-list compact"><div><dt>Người xử lý</dt><dd>{card.processedBy?.name || '—'}</dd></div></dl></section></div><section className="detail-card detail-section"><h2>Sách đã mượn</h2><div className="table-wrapper"><table className="table"><thead><tr><th>Sách</th><th>Tác giả</th><th>ISBN</th><th>Số lượng</th></tr></thead><tbody>{card.borrowedBooks.map((item, index) => <tr key={index}><td>{item.book?.title || 'Sách đã xóa'}</td><td>{item.book?.author || '—'}</td><td>{item.book?.isbn || '—'}</td><td>{item.quantity}</td></tr>)}</tbody></table></div></section><section className="detail-card detail-section"><h2>Mốc thời gian</h2><div className="timeline-grid"><div><span>Ngày mượn</span><strong>{formatDateTime(card.borrowDate)}</strong></div><div><span>Hạn trả</span><strong>{formatDateTime(card.dueDate)}</strong></div><div><span>Ngày trả</span><strong>{formatDateTime(card.returnDate)}</strong></div></div></section><div className="form-actions"><button className="btn btn-secondary" onClick={() => navigate('/borrow-cards')}>← Quay lại</button></div></div>;
}
